services:
  solid-server:
    image: solidproject/community-server:latest
    container_name: solid-server
    restart: unless-stopped

    ports:
      - "${PORT:-3000}:3000"

    volumes:
      - ./data:/data
